### ISSUE TITLE
Width and height doesn't support percentage

### ISSUE THREAD

**Issue by anundinesh** [PredixDev/px-simple-line-chart#11]
I tried passing percentage in width and height attribute, but it is not working. could you please let us know if it is possible? I have attached the screen shot for the same.
![width height](https://cloud.githubusercontent.com/assets/20392598/22737278/556cf216-edfa-11e6-812b-5c1e05e3b399.png)

**Comment by nonmetalhail** [comment]
You cannot pass in a %. The width and height are NOT CSS properties, but rather used for SVG calculations. Width and Height must be a number (in px) or "auto".
