### ISSUE TITLE
are there formatting tools for plotting timestamps on the x-axis?

### ISSUE THREAD

**Issue by weAllWeGot** [PredixDev/px-simple-line-chart#12]
couldnt find any parameters in the documentation. like for instance automatic conversion of UNIX time values to "MM-DD-YYYY" or something along those lines.

**Comment by randyaskin** [comment]
I'm a little confused by this request, as the px-simple-line-chart doesn't display _any_ values on the x-axis, it's not meant to be a detailed interactive chart but rather a quick glimpse of data on a small dashboard widget. Px-vis-timeseries provides more functionality and configurability. Could you clarify what you're asking about?

**Comment by weAllWeGot** [comment]
ah, didnt realize the px-vis-timeseries component existed, sorry! thanks.
