### ISSUE TITLE
Is there any way to publish multiseries linechart with customize filter data and zoom option?

### ISSUE THREAD

**Issue by anandmedhekar** [PredixDev/px-simple-line-chart#13]
## Screenshots 
![image](https://cloud.githubusercontent.com/assets/12048080/25495964/dfa244e2-2b9c-11e7-84f5-1fc11d43f23b.png)

Above screenshot shows customize filters for chart data through which we need to populate multiseries line chart and also allow zoom in-out option. Once the filter is applied it should hide and seek of lines should work instead of refresh of whole components everytime.

Please let me know if you need more info.

**Comment by nonmetalhail** [comment]
No, the chart just draws what you provide it. All filtering and data manipulation should be handled by the app. 

Also, simple charts are only for non-interactive, quick looks. You'll was to look at vis charts for interactivity, but still, filtering is part of the app's responsibility.

**Comment by anandmedhekar** [comment]
Do we need update chart data always after applying every filter from app or it will behave like whole chart refresh?

So do you mean to create our own component using px-vis which cover multi series line options flexibility?
Do you have any samples created using px-vis which gives interactive charts?

**Comment by nonmetalhail** [comment]
Please see the Predix UI catalog for what charts are available: https://www.predix-ui.com/#/components/px-vis-xy-chart/

It depends on what your filter is doing. Possibly you'd have to update chartData and possibly the seriesConfig. Maybe just one. If you are just switching which series is shown, you wouldnt need to change the data, just the seriesConfig.
