### ISSUE TITLE
The min label display goes below the x-axis

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-simple-line-chart#4]
The min label is displayed half near the x-axis and half is hidden below x-axis. Screen shot below:
![screen shot 2015-11-18 at 6 28 15 pm](https://cloud.githubusercontent.com/assets/7915828/11260665/31fdcfa0-8e22-11e5-86b2-ed7205e7d0a3.png)

This happens when the series data values are all 0. Sample data below:
[[1447295096554,0.0],[1447297112554,0.0],[1447299128554,0.0],[1447301144554,0.0],[1447303160554,0.0],[1447305176554,0.0],[1447307192554,0.0],[1447309208554,0.0],[1447311224554,0.0],[1447313240554,0.0],[1447315256554,0.0],[1447317272554,0.0],[1447319288554,0.0]]

Using version 1.1.0

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by randyaskin** [comment]
This was logged in Rally back in November (see issue description and discussion tabs):
https://rally1.rallydev.com/#/33932457711d/detail/defect/47159010135

**Comment by randyaskin** [comment]
Not able to replicate this in recent versions of the component.
