### ISSUE TITLE
Have errors only on IE console for px-simple-line-chart

### ISSUE THREAD

**Issue by ClaudiaHu1** [PredixDev/px-simple-line-chart#7]
![err2-2](https://cloud.githubusercontent.com/assets/15002900/14926326/88dd6a5c-0e00-11e6-8163-06430811044a.png)
Error: Unexpected call to method or property access. 

Details:
_getAxisLabelWidth: function(){
.......
var labelWidth = this.barLabel.node().getComputedTextLength(); // This line has error after we debugged.
.......
}

**Comment by mdwragg** [comment]
Hi,

I just checked this on a machine running IE11 and didn't get a console error. Also, demo page worked on IE11.

Can you submit a jsfiddle/jsbin showing the error? Please see this as an example http://jsfiddle.net/iamcap/3xyr6ppz/10/

Thanks!
Martin.

**Comment by mdwragg** [comment]
Actually, we've recreated it. @benoitjchevalier is looking into it.

**Comment by ClaudiaHu1** [comment]
![predix demo page](https://cloud.githubusercontent.com/assets/15002900/14963309/d9b2570e-1057-11e6-8596-3c0c8468cf56.png)
![co](https://cloud.githubusercontent.com/assets/15002900/14963310/db4817b6-1057-11e6-9a5f-e7d0191d12d8.png)

Hi, we tried to load the predix demo page, but it's still not working. 
     @benoitjchevalier , how the px-simple-line-chart goes? 

Thanks, 
Claudia

**Comment by mdwragg** [comment]
@ClaudiaHu1 that page is an internal URL so I've removed it. Thanks.

**Comment by benoitjchevalier** [comment]
Can you please try disabling compatibility mode and letting us know if that makes the demo page work? It renders ok on IE here without compatibility view. Polymer won't work in compatibility mode, which is basically using an older IE rendering engine

I'm looking into the IE console errors but this is not straightforward. Will let you know when I have an update. The page actually works and render correctly though, are you able to render it?

**Comment by ClaudiaHu1** [comment]
@mdwragg Thanks for the update.
@benoitjchevalier It works for the demo page. Thank you!

**Comment by benoitjchevalier** [comment]
Turns out the errors I was able to reproduce came from how the demo page generated its charts. I've fixed it, but haven't been able to produce errors from the component itself.

Please try to submit a jsfiddle/jsbin as suggested by Martin if you're still seeing issues.

**Comment by ClaudiaHu1** [comment]
@benoitjchevalier The point is the errors Only show up on IE console log(The erros is 'Unexpected call to method or property access'), the charts work fine, nothing wrong with the view of this chart. If I create a jsfiddle/jsbin, you still can't see the errors. We modified the components as a solution for our team. 

Thank you for your support!
